import { StyleSheet } from 'react-native';
import { C } from './theme';

export const s = StyleSheet.create({
  fill: { flex: 1, backgroundColor: C.cream },
  screen: { flex: 1, paddingHorizontal: 16, paddingTop: 12, backgroundColor: C.cream },
  header: { fontSize: 24, fontWeight: '800', color: C.dark, marginBottom: 12 },
  muted: { fontSize: 12, color: C.muted },
  rowBetween: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', marginBottom: 10 },
  rowCenter: { flexDirection: 'row', alignItems: 'center' },
  logoMark: { alignItems: 'center', justifyContent: 'center' },

  // Splash
  splash: { flex: 1, backgroundColor: C.yellow, alignItems: 'center', justifyContent: 'center' },
  splashLogo: { width: '50%', maxWidth: 220, aspectRatio: 1073 / 1280 },

  // Onboarding / welcome
  pill: { alignSelf: 'center', borderWidth: 1, borderColor: 'rgba(31,31,31,0.2)', borderRadius: 14, paddingHorizontal: 12, paddingVertical: 5, marginTop: 24 },
  pillText: { fontSize: 10, fontWeight: '800', color: C.dark, letterSpacing: 0.5 },
  bigWordmark: { fontSize: 44, fontWeight: '900', color: C.dark, marginTop: 20 },
  introTitle: { fontSize: 28, fontWeight: '900', color: C.dark, textAlign: 'center', marginTop: 12 },
  introBody: { fontSize: 13, color: C.dark, textAlign: 'center', lineHeight: 19, marginTop: 12, paddingHorizontal: 12 },
  footnote: { fontSize: 11, color: C.dark, textAlign: 'center', marginTop: 12, fontWeight: '600' },
  slideTop: { flex: 1.1, backgroundColor: C.yellow, borderBottomLeftRadius: 60, borderBottomRightRadius: 60, paddingHorizontal: 20, paddingTop: 50 },
  slideNav: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center' },
  slideIcon: { fontSize: 110, textAlign: 'center', marginTop: 40 },
  navWordmark: { fontSize: 16, fontWeight: '900', color: C.dark },
  skip: { fontSize: 12, fontWeight: '700', color: C.dark },
  circleSm: { width: 34, height: 34, borderRadius: 17, backgroundColor: 'rgba(255,255,255,0.7)', alignItems: 'center', justifyContent: 'center' },
  slideBottom: { flex: 0.9, padding: 24, justifyContent: 'flex-end' },
  kicker: { fontSize: 10, fontWeight: '800', color: C.yellow, letterSpacing: 0.6 },
  slideTitle: { fontSize: 28, fontWeight: '900', color: '#fff', marginTop: 8 },
  slideBody: { fontSize: 13, color: '#D6D3C8', lineHeight: 19, marginTop: 10 },
  slideFooter: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', marginTop: 22, marginBottom: 16 },
  dot: { width: 6, height: 6, borderRadius: 3, backgroundColor: '#5A5850', marginRight: 5 },
  dotActive: { width: 22, backgroundColor: C.yellow },
  counter: { fontSize: 10, color: '#A5A296', marginTop: 6 },
  nextBtn: { minWidth: 56, height: 56, borderRadius: 28, backgroundColor: C.yellow, alignItems: 'center', justifyContent: 'center', paddingHorizontal: 18 },
  nextText: { fontWeight: '800', color: C.dark, fontSize: 16 },
  heroCard: { flex: 1, backgroundColor: C.dark, borderRadius: 22, marginVertical: 24, alignItems: 'center', justifyContent: 'center' },
  heroCircle: { width: 76, height: 76, borderRadius: 38, backgroundColor: C.yellow, alignItems: 'center', justifyContent: 'center' },
  heroPill: { backgroundColor: '#fff', borderRadius: 16, paddingHorizontal: 12, paddingVertical: 6, marginTop: 14 },
  heroPillText: { fontSize: 12, fontWeight: '700', color: C.dark },
  footLink: { fontSize: 13, color: C.dark },

  // Forms
  formContent: { padding: 20, paddingBottom: 12 },
  backBtn: { width: 36, height: 36, borderRadius: 18, backgroundColor: '#fff', alignItems: 'center', justifyContent: 'center' },
  backArrow: { fontSize: 24, color: C.dark, marginTop: -3 },
  formTitle: { fontSize: 28, fontWeight: '900', color: C.dark, marginTop: 20 },
  formSub: { fontSize: 13, color: C.muted, lineHeight: 19, marginTop: 8, marginBottom: 20 },
  fieldLabel: { fontSize: 12, fontWeight: '700', color: C.dark, marginBottom: 6 },
  fieldBox: { flexDirection: 'row', alignItems: 'center', backgroundColor: '#fff', borderWidth: 1, borderColor: C.border, borderRadius: 12, paddingHorizontal: 12, height: 48 },
  fieldIcon: { fontSize: 14, marginRight: 8 },
  fieldInput: { flex: 1, fontSize: 13, color: C.dark },
  errorBox: { flexDirection: 'row', backgroundColor: C.errorBg, borderRadius: 12, padding: 12, alignItems: 'center' },
  errorText: { flex: 1, fontSize: 12, color: '#8A3B34' },
  errorPlain: { color: C.error, fontSize: 13, marginTop: 4 },
  hint: { fontSize: 11, color: C.muted, textAlign: 'center', marginTop: 20 },
  bottomBar: { paddingHorizontal: 20, paddingBottom: 16, paddingTop: 8 },
  privacy: { flexDirection: 'row', backgroundColor: C.tint, borderRadius: 10, padding: 12, marginBottom: 12, alignItems: 'center' },
  privacyText: { flex: 1, fontSize: 11, color: C.muted, lineHeight: 15 },
  primaryBtn: { backgroundColor: C.yellow, borderRadius: 12, height: 50, alignItems: 'center', justifyContent: 'center' },
  primaryBtnText: { fontSize: 14, fontWeight: '800', color: C.dark },

  // Home / shared
  homeHeader: { flexDirection: 'row', alignItems: 'center', marginBottom: 16, marginTop: 4 },
  homeTitle: { fontSize: 22, fontWeight: '900', color: C.dark, letterSpacing: 0.3 },
  bellBtn: { width: 40, height: 40, borderRadius: 20, backgroundColor: '#fff', borderWidth: 1, borderColor: C.border, alignItems: 'center', justifyContent: 'center' },
  plusBtn: { width: 40, height: 40, borderRadius: 20, backgroundColor: C.yellow, alignItems: 'center', justifyContent: 'center' },
  searchBar: { flexDirection: 'row', alignItems: 'center', backgroundColor: '#fff', borderWidth: 1, borderColor: C.border, borderRadius: 16, paddingHorizontal: 14, height: 48, marginBottom: 16 },
  quickRow: { flexDirection: 'row', justifyContent: 'space-between', marginBottom: 20 },
  quickTile: { width: '23.5%', height: 82, borderWidth: 1, borderRadius: 14, alignItems: 'center', justifyContent: 'center' },
  quickLabel: { fontSize: 11, fontWeight: '800', color: C.dark, marginTop: 8 },
  sectionTitle: { fontSize: 22, fontWeight: '900', color: C.dark, marginTop: 0, marginBottom: 2 },
  sectionSub: { fontSize: 13, fontWeight: '600', color: C.muted },
  seeAll: { fontSize: 12, fontWeight: '800', color: C.dark, backgroundColor: '#fff', borderWidth: 1, borderColor: C.border, borderRadius: 16, paddingHorizontal: 14, paddingVertical: 8, overflow: 'hidden' },
  card: { backgroundColor: '#fff', borderWidth: 1, borderColor: C.border, borderRadius: 20, padding: 12, marginBottom: 14 },
  postName: { fontSize: 14, fontWeight: '700', color: C.dark, marginRight: 6 },
  moreBtn: { width: 30, height: 30, borderRadius: 15, backgroundColor: '#F1EEE4', alignItems: 'center', justifyContent: 'center' },
  postTile: { height: 190, borderRadius: 16, padding: 12, justifyContent: 'space-between', marginVertical: 12 },
  tilePill: { backgroundColor: '#fff', borderRadius: 14, paddingHorizontal: 12, paddingVertical: 5 },
  tilePillText: { fontSize: 11, fontWeight: '800', color: C.dark },
  livePill: { backgroundColor: C.yellow, borderRadius: 14, paddingHorizontal: 12, paddingVertical: 5 },
  livePillText: { fontSize: 11, fontWeight: '800', color: C.dark },
  tileTitle: { fontSize: 17, fontWeight: '800', color: C.dark },
  tileStat: { fontSize: 12, fontWeight: '700', color: C.dark },
  avatarCircle: { backgroundColor: C.yellow, alignItems: 'center', justifyContent: 'center' },
  chip: { backgroundColor: '#fff', borderWidth: 1, borderColor: C.border, paddingHorizontal: 14, paddingVertical: 8, borderRadius: 20, marginRight: 8 },
  chipActive: { backgroundColor: C.yellow, borderColor: C.yellow },
  chipText: { fontSize: 13, color: C.muted, fontWeight: '500' },
  map: { height: 170, backgroundColor: '#E8EDD9', borderRadius: 16, alignItems: 'center', justifyContent: 'center', marginBottom: 12 },
  activityImage: { width: '100%', height: 120, borderRadius: 12, marginBottom: 6 },
  grid: { flexDirection: 'row', flexWrap: 'wrap', justifyContent: 'space-between' },
  boardCard: { width: '48%', backgroundColor: '#fff', borderWidth: 1, borderColor: C.border, borderRadius: 14, padding: 14, marginBottom: 12 },
  dateBox: { backgroundColor: C.yellow, borderRadius: 10, paddingHorizontal: 12, paddingVertical: 8 },
  dateText: { fontSize: 12, fontWeight: '800', color: C.dark, textAlign: 'center' },

  redDot: { position: 'absolute', top: 8, right: 9, width: 8, height: 8, borderRadius: 4, backgroundColor: C.orange },
  actionRow: { flexDirection: 'row' },
  actionPill: { flex: 1, flexDirection: 'row', alignItems: 'center', backgroundColor: '#F1EEE4', borderRadius: 12, paddingVertical: 11, paddingHorizontal: 12 },
  actionIcon: { fontSize: 13, marginRight: 6 },
  actionText: { fontSize: 12, fontWeight: '700', color: C.dark },

  // Profile
  darkCard: { flexDirection: 'row', alignItems: 'center', backgroundColor: C.dark, borderRadius: 18, padding: 16 },
  darkName: { fontSize: 18, fontWeight: '800', color: '#fff' },
  darkSub: { fontSize: 12, fontWeight: '700', color: C.yellow, marginTop: 2 },
  darkLink: { fontSize: 12, fontWeight: '700', color: C.yellow, marginTop: 4 },
  cameraBadge: { position: 'absolute', right: -2, bottom: -2, width: 24, height: 24, borderRadius: 12, backgroundColor: C.dark, borderWidth: 2, borderColor: '#fff', alignItems: 'center', justifyContent: 'center' },
  outlineBtn: { borderWidth: 1, borderColor: C.border, backgroundColor: '#fff', borderRadius: 12, paddingVertical: 12, alignItems: 'center' },
  outlineText: { fontSize: 14, fontWeight: '700', color: C.dark },

  // Profile (redesign)
  headerBtn: { width: 36, height: 36, borderRadius: 12, alignItems: 'center', justifyContent: 'center' },
  profileSub: { fontSize: 13, color: '#BDBAB0', marginTop: 4 },
  profileLoc: { fontSize: 12, fontWeight: '800', color: C.yellow, marginTop: 8 },
  statsRow: { flexDirection: 'row', marginTop: 12, marginBottom: 12 },
  statCard: { flex: 1, backgroundColor: '#fff', borderWidth: 1, borderColor: C.border, borderRadius: 16, paddingVertical: 16, alignItems: 'center' },
  statNum: { fontSize: 24, fontWeight: '900', color: C.dark, marginBottom: 2 },
  menuCard: { backgroundColor: '#fff', borderWidth: 1, borderColor: C.border, borderRadius: 18, padding: 14, marginBottom: 12 },
  menuRow: { flexDirection: 'row', alignItems: 'center' },
  menuIcon: { width: 34, height: 34, borderRadius: 10, alignItems: 'center', justifyContent: 'center', marginRight: 14 },
  menuLabel: { flex: 1, fontSize: 14, fontWeight: '700', color: C.dark },
  menuValue: { fontSize: 12, color: C.muted, marginRight: 10 },
  menuChevron: { fontSize: 20, color: C.muted, marginTop: -2 },
  verified: { flexDirection: 'row', alignItems: 'center', backgroundColor: '#FDF6DC', borderRadius: 16, padding: 14 },
  verifiedText: { flex: 1, fontSize: 14, fontWeight: '700', color: C.dark },
  yearPill: { backgroundColor: '#fff', borderWidth: 1, borderColor: C.border, borderRadius: 16, paddingHorizontal: 16, paddingVertical: 8 },
  yearPillText: { fontSize: 14, fontWeight: '700', color: C.dark },
  profileActions: { flexDirection: 'row', paddingHorizontal: 16, paddingVertical: 10, backgroundColor: C.cream },
  profileBtn: { flex: 1, height: 46, borderRadius: 14, flexDirection: 'row', alignItems: 'center', justifyContent: 'center' },
  profileBtnText: { fontSize: 14, fontWeight: '800', color: C.dark },

  // Logout modal
  scrim: { flex: 1, backgroundColor: 'rgba(31,31,31,0.4)', justifyContent: 'center', paddingHorizontal: 18 },
  modalCard: {
    backgroundColor: C.cream, borderRadius: 24, padding: 18,
    shadowColor: '#000', shadowOpacity: 0.18, shadowRadius: 20, shadowOffset: { width: 0, height: 8 }, elevation: 10,
  },
  modalIcon: { width: 40, height: 40, borderRadius: 12, backgroundColor: '#FDF1C4', alignItems: 'center', justifyContent: 'center', marginBottom: 16 },
  doorBracket: { width: 9, height: 16, borderWidth: 1.8, borderRightWidth: 0, borderColor: C.dark, borderTopLeftRadius: 3, borderBottomLeftRadius: 3 },
  doorArrow: { fontSize: 15, fontWeight: '700', color: C.dark, marginLeft: -3, marginTop: -2 },
  modalTitle: { fontSize: 22, fontWeight: '900', color: C.dark },
  modalBody: { fontSize: 13, color: C.muted, marginTop: 8, lineHeight: 19 },
  modalActions: { flexDirection: 'row', marginTop: 20 },
  modalBtn: { flex: 1, height: 52, borderRadius: 14, alignItems: 'center', justifyContent: 'center' },
  modalCancel: { backgroundColor: '#fff', borderWidth: 1, borderColor: C.border, marginRight: 12 },
  modalBtnText: { fontSize: 14, fontWeight: '800', color: C.dark },

  // Tab bar
  tabBar: { flexDirection: 'row', backgroundColor: C.dark, paddingTop: 10, paddingBottom: 18 },
  tabItem: { flex: 1, alignItems: 'center' },
  tabIcon: { fontSize: 18, opacity: 0.55 },
  tabLabel: { fontSize: 10, color: '#A5A296', marginTop: 3 },
});
